---

- name: 'create sonar database'
  mysql_db: name=sonar state=present
#            login_user=root login_password={{mysql_root_password}}
  when: features.mysql
  tags:
    - sonar
    - sonarconfig
    - database
    - mysql

- name: 'create sonar user'
  mysql_user: name={{ sonar_username }} priv=sonar.*:ALL
    password={{ sonar_password }}
#    login_user=root login_password={{mysql_root_password}}
  when: features.mysql
  tags:
    - sonar
    - sonarconfig
    - database
    - mysql

- name: 'create sonar database'
  postgresql_db: name=sonar template='template0'
                 encoding='UTF-8'
                 #lc_collate='en_EN.UTF-8' lc_ctype='en_EN.UTF-8'
  when: features.postgresql
  tags:
    - sonar
    - sonarconfig
    - database
    - postgresql

- name: 'create sonar user'
  postgresql_user: db=sonar name='{{sonar_username}}' password='{{sonar_password}}'
  when: features.postgresql
  tags:
    - sonar
    - sonarconfig
    - database
    - postgresql

- name: 'configure sonar.properties'
  template:
    src: ../templates/sonar.properties
    dest: "{{ sonar_home }}/{{ sonar_name }}/conf/sonar.properties"
    mode: 0644
    backup: off
    force: True
  notify: restart sonar
  tags:
    - sonar
    - sonarconfig

