---
- name: 'make sure sonar plugins are installed'
  get_url: url={{item}}
             owner=sonar group=sonar mode=0644
             dest=/opt/sonar/extensions/plugins
  with_items: sonar_plugins
  notify:
  - 'restart sonar'
